development: &DEV
  root_url:         http://localhost:3000/
  sports_data_url:  http://sports.playupgp.com/
  web_socket_host:  localhost
  web_socket_port:  5555

test:
  <<: *DEV

systest:
  <<: *DEV
  root_url:         http://systest.tms.playupdev.com:8282/
  web_socket_host:  systest.tms.playupdev.com

production:
  <<: *DEV