development: &DEV
  root_url:         http://localhost:7777/
  sports_data_url:  http://sports.playupgp.com/
  web_socket_host:  localhost
  web_socket_port:  5555

test:
  <<: *DEV

systest:
  <<: *DEV
  root_url:         http://systest.tms.playupdev.com:8282/
  web_socket_host:  tmssystest-TMSELB-12REHUEL06NXT-1389627696.us-west-2.elb.amazonaws.com

production:
  <<: *DEV