development: &DEV
  root_url:         http://localhost:7777/
  sports_data_url:  http://sports.playupgp.com/
  web_socket_host:  localhost
  web_socket_port:  5555

test:
  <<: *DEV

systest:
  <<: *DEV
  root_url:         http://systest.tms.playupdev.com:8282/
  web_socket_host:  ec2-50-112-219-61.us-west-2.compute.amazonaws.com

production:
  <<: *DEV